name: pingPlugin
version: 1.2
author: 3urobeat
main: org.x3urobeat.pingPlugin.Main
description: Tells you your or the ping of another player in ms to the server

commands:
  ping:
    description: See your ping in ms to the server
  pinginfo:
    description: What's this? (Help)
